language: node_js
node_js:
- node
env:
  global:
  - secure: KUvCJb/xqiiefX+9RmTFQeIFs7y70e4UINizrdMmOhvesiY+Zhr8Dcz1+kV5dvmEXxE0HwU+h5QWiIyGc2BNHJJ78C6tg2KfCWsOqkMKuzUyRug7L5SmOGejAQvCmCFgatgFKEzoC+qk0FMFM3KkrZMEj63tMKvHhnqpEWp4rXHIUbqvmUCi6GFFZxMUtx6JG3dOCji9lNoH2hyPo+ilNotgMeA1cZc0OiqAz87xfyee9N6TgIBHGmKDGNvvjCTyyWBp+/beNF9EP8SA57YfFvZmw5CH9JfVOiP4TR4fpBUzdzQrpAPbh1eXcksSGtrBrBFpQTJU8Hf+bDQHDaDp7XM9I+JeC11o1o6fe7IeFSOQDHVnYpYXah3I3cUM3oG7UV3Jr6GCl3c5gh+kB56YFb78fgoTMsXKUMbfiUMG+S2HM98U88fDoW20u7bLwFs5GEG3JQz/UeUGlVe5cJWa7x9WsMzfjVGQwK2qPah9hrU8T6aKkRXQQJjqzrs7/rbWMi3Fq4SZSRT0tmGzBDsiIGDwRu7yI0F4knAGIf8Y2f1isXfdg9flasf7Ed3ebsV75UFoztcJzoM+UqVmVoclYg8QKo5bfNoAfgSiC4lQMF4+HTUyTr/Ld2GTPx3EnhlbjnOoVspW7fO1G+8qWTg1+8RsoohUIVo5qsOK6y/gAng=
deploy:
  provider: npm
  email: me@leonidumanskiy.com
  api_key:
    secure: MHpwmLiYYgqkSCdOBlmQPZ0HL100qSdM6AF5yrndiF6Z+Jef/xGkonHpdUQYSlFR/SQs1A3wRl4yQPKjcTImLLSlyc7wr19LYL6o3bbvUtJ52MvxhRusPqVrFlOdg/8aMIuRt7QqG9Icwr33rW2Ujb95+cI2gSYN2TcqFkD7oM9oRDilQpBVvjWQdFawaYz0l+ttoxLuB+AQ4rmUkk7pghLCT4+no7TTiSx2SmQG1HTItceTUCB1C7o5aT0sCTkACG2hletfKMBrTSvqAKXJsbPJeBiP8X71jdVXLvWE/D88ZYVL/yU7fGAZU4W+2Py7sbpq8oQFNTnGJIHxrrhFOUvLNGIvUOcX2pCs+f3KOAs74DudQbD5HZuEdzbbDnrqeR29DA4wyFfYrNFWoF/99p8OG6kCpAvWbgju0xPXh1q+7bwy+kkdMk6O0OMCi5ITHleWpIe8T5x8KHgozB7lCSoNWlv0C6aii/qbk71cS4o26wVJ7yOpQn0qnzoVIDlUcClym2QLWJX3QBMqy4nJ2cZcdk+euy25OUfJHrVk5/jCrSSOvjPrbRi8fjZ0Mah23PBc4F048lt3kOVI1Glt42EcRT1KCZUEGVI/qTAppTxTG6SizdV3pPcDu9BFYjxEpry7B23k7+ELtpAoWf3EICSPVUC5ldF78SWhtMqgDNA=
  on:
    tags: true
    repo: rdata-systems/rdata-server-jwt-auth
