language: node_js
node_js:
- node
env:
 global:
   - secure: KUvCJb/xqiiefX+9RmTFQeIFs7y70e4UINizrdMmOhvesiY+Zhr8Dcz1+kV5dvmEXxE0HwU+h5QWiIyGc2BNHJJ78C6tg2KfCWsOqkMKuzUyRug7L5SmOGejAQvCmCFgatgFKEzoC+qk0FMFM3KkrZMEj63tMKvHhnqpEWp4rXHIUbqvmUCi6GFFZxMUtx6JG3dOCji9lNoH2hyPo+ilNotgMeA1cZc0OiqAz87xfyee9N6TgIBHGmKDGNvvjCTyyWBp+/beNF9EP8SA57YfFvZmw5CH9JfVOiP4TR4fpBUzdzQrpAPbh1eXcksSGtrBrBFpQTJU8Hf+bDQHDaDp7XM9I+JeC11o1o6fe7IeFSOQDHVnYpYXah3I3cUM3oG7UV3Jr6GCl3c5gh+kB56YFb78fgoTMsXKUMbfiUMG+S2HM98U88fDoW20u7bLwFs5GEG3JQz/UeUGlVe5cJWa7x9WsMzfjVGQwK2qPah9hrU8T6aKkRXQQJjqzrs7/rbWMi3Fq4SZSRT0tmGzBDsiIGDwRu7yI0F4knAGIf8Y2f1isXfdg9flasf7Ed3ebsV75UFoztcJzoM+UqVmVoclYg8QKo5bfNoAfgSiC4lQMF4+HTUyTr/Ld2GTPx3EnhlbjnOoVspW7fO1G+8qWTg1+8RsoohUIVo5qsOK6y/gAng=
